spring.application.name=dompetku

# Kalau ingin run backend, buat file .env dan jalankan ini dari folder backend:
# export $(cat .env | grep -v '^#' | xargs) && ./gradlew bootRun
# Server Configuration
server.port=${SERVER_PORT:7860}

# PostgreSQL Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=${JWT_SECRET}
